### ISSUE TITLE
inconsistencies in setup.json

### ISSUE THREAD

**Issue by ltalirz** [pzarabadip/aiida-scheduler-bundle#1]
Hi @pzarabadip , I'm not quite sure why the plugin registry didn't pick up the entry points provided by your plugin

![image](https://user-images.githubusercontent.com/1053245/95792361-a5944800-0ce3-11eb-8709-f4ae15256809.png)

 but looking at the setup.json there definitely are a couple of inconsistencies

- [x] "url"
- [x] "entry_points"

**Comment by ltalirz** [comment]
It seems it was unable to parse the json: https://github.com/aiidateam/aiida-registry/runs/1244218157#step:6:11

**Comment by ezpzbz** [comment]
Sorry @ltalirz 
I overlooked that entry points and there was a typo in url. These should be fixed now.

**Comment by ltalirz** [comment]
Thanks, looks fine to me.
The registry will fetch the update automatically within 24h.
